module.exports = {
  courses: [
    {
      course_id: 877922,
      description: null,
      name: "Angels on Earth Master Class",
      heading: "Time to Rise and Shine",
      is_published: true,
      image_url:
        "https://file-uploads.teachablecdn.com/a5c9d7733f594c7b8bf927f2f5b75da1/6b1be8c53fff45dbb2aa95d0c6a17888",
      sections: [
        {
          section_id: 3385791,
          name: "Section #1 Day #1 - Welcome to the Program",
          is_published: true,
          position: 1,
          lectures: [
            {
              lecture_id: 15979010,
              name: "Know Your Facilitator",
              position: 1,
              is_published: true,
              lecture_section_id: 3385791,
            },

            {
              lecture_id: 15979204,
              name: "Bird's Eye View",
              position: 2,
              is_published: true,
              lecture_section_id: 3385791,
            },
            {
              lecture_id: 31391689,
              name: "Make the Most of the Program",
              position: 3,
              is_published: true,
              lecture_section_id: 3385791,
            },
            {
              lecture_id: 15979229,
              name: "What is Angels on Earth?",
              position: 4,
              is_published: true,
              lecture_section_id: 3385791,
            },
            {
              lecture_id: 15979225,
              name: "Angels Meditation",
              position: 5,
              is_published: true,
              lecture_section_id: 3385791,
            },
            {
              lecture_id: 15979309,
              name: "What are Angels?",
              position: 6,
              is_published: true,
              lecture_section_id: 3385791,
            },
            {
              lecture_id: 31391691,
              name: "GoodBye Message for Today",
              position: 7,
              is_published: true,
              lecture_section_id: 3385791,
            },
            {
              lecture_id: 40299117,
              name: "New Lecture",
              position: 8,
              is_published: false,
              lecture_section_id: 3385791,
            },
          ],
        },

        {
          section_id: 3385859,
          name: "Section 2 - Day #2 - FAQs about Angels?",
          is_published: true,
          position: 2,
          lectures: [
            {
              lecture_id: 15979344,
              name: "Do we pray to Angels",
              position: 1,
              is_published: true,
              lecture_section_id: 3385859,
            },
            {
              lecture_id: 15979330,
              name: "What do Angels look like?",
              position: 2,
              is_published: true,
              lecture_section_id: 3385859,
            },
            {
              lecture_id: 15979352,
              name: "How do I contact my Angels?",
              position: 3,
              is_published: true,
              lecture_section_id: 3385859,
            },
            {
              lecture_id: 15979390,
              name: "What is Angel's Altar?",
              position: 4,
              is_published: true,
              lecture_section_id: 3385859,
            },
            {
              lecture_id: 16132524,
              name: "What are Archangels ?",
              position: 5,
              is_published: true,
              lecture_section_id: 3385859,
            },
            {
              lecture_id: 15979420,
              name: "Archangel Connection Exercise",
              position: 6,
              is_published: true,
              lecture_section_id: 3385859,
            },
            {
              lecture_id: 31396690,
              name: "Today's Good Bye Message",
              position: 7,
              is_published: true,
              lecture_section_id: 3385859,
            },
          ],
        },

        {
          section_id: 3385877,
          name: "Section 3 - Day #3 - Connecting with Archangels",
          is_published: true,
          position: 3,
          lectures: [
            {
              lecture_id: 15979426,
              name: "Archangel Micheal",
              position: 1,
              is_published: true,
              lecture_section_id: 3385877,
            },
            {
              lecture_id: 15979433,
              name: "Archangel Gabriel",
              position: 2,
              is_published: true,
              lecture_section_id: 3385877,
            },
            {
              lecture_id: 15979512,
              name: "Archangel Azrael",
              position: 3,
              is_published: true,
              lecture_section_id: 3385877,
            },
            {
              lecture_id: 15979550,
              name: "Archangel Raziel",
              position: 4,
              is_published: true,
              lecture_section_id: 3385877,
            },
            {
              lecture_id: 15979628,
              name: "Archangel Ariel",
              position: 5,
              is_published: true,
              lecture_section_id: 3385877,
            },
            {
              lecture_id: 15979643,
              name: "Archangel Metatron",
              position: 6,
              is_published: true,
              lecture_section_id: 3385877,
            },
            {
              lecture_id: 31399553,
              name: "Today's Good Bye Message",
              position: 7,
              is_published: true,
              lecture_section_id: 3385877,
            },
          ],
        },

        {
          section_id: 3385941,
          name: "Section 4 - Day #4 - Connecting with Archangels (....continued)",
          is_published: true,
          position: 4,
          lectures: [
            {
              lecture_id: 15979695,
              name: "Archangel Chamuel",
              position: 1,
              is_published: true,
              lecture_section_id: 3385941,
            },
            {
              lecture_id: 15979700,
              name: "Archangel Uriel",
              position: 2,
              is_published: true,
              lecture_section_id: 3385941,
            },
            {
              lecture_id: 15979742,
              name: "Archangel Sandolphon",
              position: 3,
              is_published: true,
              lecture_section_id: 3385941,
            },
            {
              lecture_id: 16324199,
              name: "Archangel Jophiel",
              position: 4,
              is_published: true,
              lecture_section_id: 3385941,
            },
            {
              lecture_id: 15979789,
              name: "Archangel Haniel",
              position: 5,
              is_published: true,
              lecture_section_id: 3385941,
            },
            {
              lecture_id: 15979794,
              name: "Archangel Raguel",
              position: 6,
              is_published: true,
              lecture_section_id: 3385941,
            },
            {
              lecture_id: 15979801,
              name: "Archangel Jeremiel",
              position: 7,
              is_published: true,
              lecture_section_id: 3385941,
            },
            {
              lecture_id: 16332610,
              name: "Archangel Zadkiel",
              position: 8,
              is_published: true,
              lecture_section_id: 3385941,
            },
            {
              lecture_id: 15979805,
              name: "Archangel Raphael",
              position: 9,
              is_published: true,
              lecture_section_id: 3385941,
            },
            {
              lecture_id: 31399556,
              name: "Today's Good Bye Message",
              position: 10,
              is_published: true,
              lecture_section_id: 3385941,
            },
          ],
        },

        {
          section_id: 3385942,
          name: "Section 5 - Day #5 -  More on Archangels",
          is_published: true,
          position: 5,
          lectures: [
            {
              lecture_id: 16357932,
              name: "Bonus Sharing",
              position: 1,
              is_published: true,
              lecture_section_id: 3385942,
            },
            {
              lecture_id: 16382319,
              name: "Completion Message",
              position: 2,
              is_published: true,
              lecture_section_id: 3385942,
            },
            {
              lecture_id: 22399230,
              name: "Ready Reckoner",
              position: 3,
              is_published: true,
              lecture_section_id: 3385942,
            },
            {
              lecture_id: 17356662,
              name: "Archangel Connection Guided Meditation",
              position: 4,
              is_published: true,
              lecture_section_id: 3385942,
            },
            {
              lecture_id: 31417090,
              name: "Today's Good Bye Message",
              position: 5,
              is_published: true,
              lecture_section_id: 3385942,
            },
          ],
        },

        {
          section_id: 9026404,
          name: "AOE Meditations",
          is_published: true,
          position: 6,
          lectures: [
            {
              lecture_id: 47406537,
              name: "Most Powerful Archangels Meditations",
              position: 1,
              is_published: true,
              lecture_section_id: 9026404,
            },
          ],
        },

        {
          section_id: 4481035,
          name: "AOE Advanced Manual",
          is_published: true,
          position: 7,
          lectures: [
            {
              lecture_id: 23264257,
              name: "AOE Advanced Manual",
              position: 1,
              is_published: true,
              lecture_section_id: 4481035,
            },
          ],
        },

        {
          section_id: 5834798,
          name: "AOE Quiz",
          is_published: true,
          position: 8,
          lectures: [
            {
              lecture_id: 31601648,
              name: "New Lecture",
              position: 1,
              is_published: false,
              lecture_section_id: 5834798,
            },
            {
              lecture_id: 47406531,
              name: "New Lesson",
              position: 2,
              is_published: false,
              lecture_section_id: 5834798,
            },
          ],
        },
      ],
    },
  ],
};
